### PR TITLE
Fix type parameter resolution for pardefs. Fix #212

### LINKED ISSUE #212: `foldr` fails on code that `foldl` accepts
The following code fails to typecheck:

    Int f1 = foldr((Int elem, Int acc) => elem + acc)(list[1, 2, 3], 0);

If `foldr` is replaced by `foldl`, the code compiles.

### PR DESCRIPTION
**Pull request by BjoernPetersen**

### CODE REVIEW

**Comment by rudi** [comment]
Thanks for having a look!  Unfortunately this broke the unit test for `filter`; check with

    List<Int> ff = filter((Int x) => x % 2 == 0)(list[1, 2, 3]);

There's also another one, exhibited by the straightforward definition of `flatten` (discovered by Einar)

    def List<A> flatten<A>(List<List<A>> l) = foldl(concatenate)(l, Nil);

**Comment by BjoernPetersen** [comment]
Whoops, sorry! Not sure, how I missed that.

**Comment by BjoernPetersen** [comment]
This opened up a whole can of worms. It'll probably take about two weeks until I get around to this.

**Comment by BjoernPetersen** [comment]
I think this is working now.  
For AllTests I get 10 failures before and after these changes, the StdLibTests pass now.  
I also tested your filter and flatten examples and they are working, too.The flatten definition has been added as an additional test case.

**Comment by rudi** [comment]
Many thanks!  I'm traveling this week and am on Hotel Internet, but I'll get to it soon.

**Pull request merged**
