### PR TITLE
WIP: Try to fix CircleCI build

### PR DESCRIPTION
**Pull request by BjoernPetersen**
I can't recreate the error on my fork, so I'm hijacking this PR to try some things that might fix the CircleCI build.

### CODE REVIEW

**Comment by rudi** [comment]
Seems to work now, thanks!  (I guess I should add you to the abstools team so you can see the circleci page yourself, sounds good?)

**Comment by BjoernPetersen** [comment]
Sounds good! I'll try not to break things.

**Comment by rudi** [comment]
Check if you can already access https://circleci.com/team/gh/abstools after being added to the team

**Comment by BjoernPetersen** [comment]
I do have access, thanks for adding me!

**Pull request merged**
