### PR TITLE
Fix for tests, which do not terminate

### PR DESCRIPTION
**Pull request by ahbnr**
The deadlock tests do not terminate for me. Since it seems this is caused by reading input from dead threads, my changes close the used streams and introduce checks, whether the involved thread terminated etc.

Example log of running tests which did not terminate: https://ahbnr.de/jenkins/job/abstools-master/1/consoleFull

Log of executing tests after the changes introduced by this pull request have been applied: https://ahbnr.de/jenkins/job/abstools-mod/21/consoleFull

Also an optional property `excludeTests` has been added to the `build.gradle`. It allows to exclude tests when invoking gradle. Example:

`gradle test -PexcludeTests='**/ErlangModelApiTests*,**/ErlangExamplesTests*'`

### CODE REVIEW

**Comment by ahbnr** [comment]
As you can see in the second log (or in the corresponding test summary: https://ahbnr.de/jenkins/job/abstools-mod/21/testReport/), there are 267 tests of 1246 which fail for me.

Does this only happen in my build environment, or do others get the same results?

**Comment by rudi** [comment]
Hmm, in the master branch, I get the usual 2-3 failures (which I plan to fix by removing the Maude backend, as mentioned at the recent workshop).  With your branch, I get 269 failures, including all erlang tests.  It seems the erlang backend cannot find the result value.

Could it be that after the `while(p.isAlive())` loop has exited, we should do another round of reading from the output buffer, just in case the process was very quick in finishing?

**Comment by rudi** [comment]
Sorry for taking so long to look at this.  Just checking -- how many test failures do you get on this branch?  I'm asking since I get 4 failures on master but 269 with this pull request, and want to make sure I'm testing the right thing.

**Comment by ahbnr** [comment]
> �Sorry for taking so long to look at this. Just checking -- how many test failures do you get on this branch? I'm asking since I get 4 failures on master but 269 with this pull request, and want to make sure I'm testing the right thing.

You are testing the right thing, since it seems you are right about the `while(p.isAlive())` issue. I already began fixing this, but didn't complete it yet, because I am unfortunately occupied with something else at the moment. I will try to push a fix soon, until then the merge request should be put on hold.

**Comment by ahbnr** [comment]
Ok, now with my latest commit on the branch in question, all tests but 1 Maude test complete successfully:

https://ahbnr.de/jenkins/job/abstools-mod/lastCompletedBuild/testReport/

**Comment by rudi** [comment]
Thanks!

**Pull request merged**
