### PR TITLE
Fix constant folding for #283

### PR DESCRIPTION
**Pull request by DerDrodt**
Fixes the rewrite of unary minus as mentioned in #283.

When a `MinusExp` gets rewritten, it is first checked, if the inner constant starts with a "-". If it does, the resulting `IntegerLiteral` will simply remove this minus.

### CODE REVIEW

**Comment by rudi** [comment]
Very cool, thanks!  Could you add a unit test so this bug stays nailed down and fixed?  Taking the expression from #283 and putting it somewhere in https://github.com/abstools/abstools/blob/master/frontend/src/test/java/org/abs_models/backend/common/PrimitiveTypes.java should be fine.

**Comment by DerDrodt** [comment]
> Very cool, thanks! Could you add a unit test so this bug stays nailed down and fixed? Taking the expression from #283 and putting it somewhere in https://github.com/abstools/abstools/blob/master/frontend/src/test/java/org/abs_models/backend/common/PrimitiveTypes.java should be fine.

Working on that right now :)

**Comment by DerDrodt** [comment]
I have added the test now.

**Comment by rudi** [comment]
Fantastic, thanks! Merged.
(If you add something like `fixes: #283` to the commit message, the bug will automagically close; I closed #283 manually just now.)

**Comment by DerDrodt** [comment]
> (If you add something like `fixes: #283` to the commit message, the bug will automagically close; I closed #283 manually just now.)

I knew I forgot something. Thanks!

**Pull request merged**
