### PR TITLE
Fix frontend Maven build

### PR DESCRIPTION
**Pull request by BjoernPetersen**
This fixes the Maven build file and completely moves dependency management to Maven.

The frontend jarfile _can_ now be built by executing `mvn package` in the frontend directory. 

The ant build is still the reference build for distribution. It will now use the Maven dependency plugin to access the project dependencies.

### A few things to note:
- The old parent pom has been abandoned for now as it is completely outdated
- I chose the group ID `org.abs-models` and the artifact ID `absfrontend`
- Ant will generate and compile files in suitable subdirectories of `target` now
- There is no Maven plugin to run JastAdd, so the antrun-plugin is used for that

### Limitations:
- The jar built by Maven will not contain the full manifest
- Only the frontend tests can be executed with Maven by using the `tests-frontend` profile (`mvn test -P tests-frontend`)
- Advanced tasks such as building the eclipse plugin or running findbugs currently can't be done with Maven

### Why this is a good change:
- (Almost) no more binary files in the git repository
- Dependency versions only have to be updated in one place
- The project can be imported as a Maven project in any IDE

### Further considerations:
- The eclipse project files _could_ be deleted from version control at some point in the future
- I am not sure why build.properties is checked in to version control

### CODE REVIEW

**Comment by rudi** [comment]
With this patch, the unit tests hang in test `caseBoundLocalField[JavaBackend]`.  Compiling and running the file `frontend/tests/abssamples/backend/FunctionalTests/caseBoundLocal.abs` (which is run by the hanging test) works.

In the log, I see lots of instances of the message `Exception in thread "ABS Scheduler Thread of COG [Main] (1)" java.lang.NoClassDefFoundError: org/apfloat/Aprational` followed by a stack trace.  Not sure if this is related.

**Comment by BjoernPetersen** [comment]
That's interesting, apfloat (including that class) should definitely be on the classpath. I'll have a more in-depth look at it

**Comment by VolkerStolz** [comment]
> I am not sure why build.properties is checked in to version control

Try deleting it and see if Eclipse is still happy?

**Comment by BjoernPetersen** [comment]
@VolkerStolz I did and can't make out any difference. There doesn't seem to be any explicit reference to the file in the project. What's its use? I originally assumed it could be used to overwrite properties in the build.xml, but I think it would need to be imported in the build.xml for that, which it isn't.

**Comment by rudi** [comment]
It's always possible it was checked because of ignorance.  If we remove it, let's do it in a separate commit though so it can be reverted more easily.

**Comment by VolkerStolz** [comment]
I think it's (at least) used to assemble the plugin JAR when you export it from Eclipse.

  Volker

**Comment by BjoernPetersen** [comment]
OK, I wasn't aware the plugin build process was so intertwined with the frontend build. Because of that and the backend tests doing what they're doing, this PR will have to wait until next year.

**Comment by BjoernPetersen** [comment]
This (or a Gradle build file) is still something I think this project should have, but getting it right would be a lot of work and probably break some stuff. Since I don't have the time to finish this, I'm closing the pull request for now.

**Comment by rudi** [comment]
If it was only the eclipse plugin process that killed this, I'd rather delete the eclipse plugin now than abandon this effort.  Last time I tried the plugin, it was *severely* broken, and a student of Radu's is developing a new plugin based on Xtext, which is a much more sensible thing to do.

**Comment by rudi** [comment]
FWIW, the only thing keeping me from deleting the existing eclipse plugin outright is that there's some other plugins hanging in that directory.  I was planning to discuss handing over plugin responsibility to the tool developers at the workshop; let's keep this issue open until then?  OTOH, @BjoernPetersen if it wasn't only the eclipse plugin issue, then feel free to re-close.

**Comment by rudi** [comment]
Closing this again -- the eclipse plugin is gone but we'll likely switch to gradle instead of maven.

**Comment by rudi** [comment]
Given that the move to gradle will entail reorganization of the directory structure, feel free to also rename the `frontend/` directory to something more meaningful (`compiler/` maybe?)

**Pull request closed without merging**
