### PR TITLE
Fix trait import/export

### LINKED ISSUE #180: Traits don't work across modules
Currently a trait cannot be used in a module other than the module where it is defined. Example:

```
module A;
import * from B;
class A {
   uses T;
}

module B;
export T;
class B {
   uses T;
}
trait T = {}
```

gives an error: `couldn't resolve trait: T`

### PR DESCRIPTION
**Pull request by BjoernPetersen**
**Note:**
6 additional tests from the `abs.frontend.delta` package are failing. Those tests also failed before, but weren't executed, because only a subset of the test files were included in the `AllFrontendTests` test suite. I created a `DeltaTests` suite containing all delta tests and added it to `AllFrontendTests` instead of the indiviual files.

Also I couldn't keep myself from fixing code formatting issues in the files I touched, sorry about the confusing diff.

Fixes #180

### CODE REVIEW

**Comment by rudi** [comment]
Thanks for looking at this!

Unfortunately this change breaks some tests, see e.g.:
```
cd frontend/examples/SmartHome/abs ; absc *.abs
```
which fails with a NullPointerException at abs.frontend.ast.TraitExpr.resolve(TraitExpr.java:103).

It's possible that the examples are outdated / invalid but nevertheless the compiler should not terminate with a stack trace.

**Comment by BjoernPetersen** [comment]
I'll have a look at it

**Comment by BjoernPetersen** [comment]
The tests pass now. As far as I can tell, no new frontend tests are failing.

**Comment by BjoernPetersen** [comment]
I don't want to seem impatient, but just in case the last message got overlooked: this PR should be ready to merge.

**Comment by rudi** [comment]
Merged - thanks for working on this!

**Pull request merged**
