### PR TITLE
Computation of free variables did not consider list literals.

### PR DESCRIPTION
**Pull request by ahbnr**
The issue described in the title causes compiler errors when creating closures which use variables in list literals.

Example:
```
module MinimalExample;

def List<Int> run(fun)() = fun();

// This causes a compiler error on master, since a global function is constructed
// from the anonymous one, deducing the parameters from all free variables.
// However, free variables inside list literals are not considered.
// Error message: "Name r0 cannot be resolved."
def List<Int> test(Int r0) = run(
    () => list[r0]
  )();

{
  println("Main block");
}
``` 

The changes introduced by this branch adjust FreeVars.jrag to consider ListLiterals.
Also two tests have been added.

Building the branch results in no issues but 1 known test failure regarding the Maude backend:
https://ahbnr.de/jenkins/job/abstools-lambdaFunListLiteralVarsFix/4/testReport/

### CODE REVIEW

**Comment by VolkerStolz** [comment]
Haven't checked for technical correctness, but this patch is as good as it gets: (failing) test case + fix.
I wish more people would submit detailed pull-requests...

**Comment by ahbnr** [comment]
I noticed too late that the branch is still based on an older version of master. I'd like to merge with the upstream master and run a few tests first, before I reopen the pull request

**Comment by rudi** [comment]
Likewise :)

I’m on 2G internet until next Monday, will check and merge early next week.

**Comment by ahbnr** [comment]
While running the tests in this branch I again encountered tests which sometimes did not terminate (see #254).

Before reopening this pull request, I'd like to first discuss and fix this issue: https://github.com/abstools/abstools/pull/258

**Comment by rudi** [comment]
Could I ask you to use different feature branches for the pull requests?  This request contains commits that are already merged via #254, so it's not easy to see what to review.
Thanks for working on this!

**Comment by rudi** [comment]
Ah sorry - I see that this was originally its own branch but another branch was merged in in commit 
0672b24.  You could revert that commit and do a forced push.  Since we're rewriting history, you could also merge commits 43094a2 and baeef68 via an interactive rebase (`git rebase -i 43094a2~2`, or something similar)

**Comment by ahbnr** [comment]
Since #259 has been resolved, I created a copy of this pull request based on a fresh branch: #260

**Pull request closed without merging**
